inherit_from: ./common.yaml

data:
  output: /srv/szha0669/unblur-slam/slam_paired/fr2_xyz_fixed_kf_resplat3_fusion_221_v6_virtual_count_bugfix/evssm_resplat3_virtual_count_bugfix

mapping:
  official_resplat_active_fusion:
    enabled: true
