inherit_from: ./common.yaml

mapping:
  mip_splatting:
    enabled: true
    filter_kernel_variance: 0.2

data:
  output: /srv/szha0669/unblur-slam/slam_paired/fr2_xyz_online_mip_resplat_main_v1/mip_splatting
